[package]
name = "ogma-shell"
version = "0.1.0"
authors = ["kurt <kurtlawrence92@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
# workspace
ogma =    { path = "../ogma" }
ogma-ls = { path = "../ogma-ls" }

# kdr-aus git
divvy = { git = "https://github.com/kdr-aus/divvy" }

# crates.io
cansi =	"2"
colored = "2"
crossbeam = "0.8"
crossterm = "0.20"
fastrand = "1"
fxhash = "0.2"
tui = { version = "0.16", default-features = false, features = [ "crossterm" ] }
unicode-width = "0.1"
