[package]
name = "ogma"
version = "0.1.0"
authors = ["kurt <kurtlawrence92@gmail.com>"]
edition = "2018"

[dependencies]
# kdr-aus git
divvy = { git = "https://github.com/kdr-aus/divvy" }
numfmt = { git = "https://github.com/kdr-aus/numfmt" }
table = { git = "https://github.com/kdr-aus/table" }

# crates.io
colored = "2"
comfy-table = "4"
fastrand = "1"
fxhash = "0.2"
kserd = "0.5"
lazy_static = "1"
nom = "6"
parking_lot = "0.11"
paste = "1"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["formatting", "macros"] }
