name: Markdown linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: MarkdownLint mdl Action
        uses: actionshub/markdownlint@2.0.2
        
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
    
